### ISSUE TITLE
Improve Error message for DEM lookup fail

### ISSUE THREAD

**Issue by ASVincent** [GeoscienceAustralia/wagl#216]
There is no human readable error message for the failure to lookup a value from the DEM.
Discussion within the team revealed that this error may occur on a granule deemed valid where there is an overlap between the granule and the valid geospatial extent of the underlying ancillary. 
~~~~
Stacktrace:
Traceback (most recent call last):
File "../python3.6/site-packages/luigi/worker.py", line 194, in run
new_deps = self._run_get_new_deps()
File "../python3.6/site-packages/luigi/worker.py", line 131, in _run_get_new_deps
task_gen = self.task.run()
File "../python3.6/site-packages/wagl-5.0.3+2.g69df1a4-py3.6-linux-x86_64.egg/wagl/singlefile_workflow.py", line 103, in run
self.buffer_distance, self.compression, self.acq_parser_hint)
File "../python3.6/site-packages/wagl-5.0.3+2.g69df1a4-py3.6-linux-x86_64.egg/wagl/standardise.py", line 152, in card4l
vertices, root, compression)
File "../python3.6/site-packages/wagl-5.0.3+2.g69df1a4-py3.6-linux-x86_64.egg/wagl/ancillary.py", line 187, in collect_ancillary
compression=compression, **nbar_paths)
File "../python3.6/site-packages/wagl-5.0.3+2.g69df1a4-py3.6-linux-x86_64.egg/wagl/ancillary.py", line 397, in collect_nbar_ancillary
elev = get_elevation_data(geobox.centre_lonlat, dem_path)
File "../python3.6/site-packages/wagl-5.0.3+2.g69df1a4-py3.6-linux-x86_64.egg/wagl/ancillary.py", line 593, in get_elevation_data
data = get_pixel(datafile, lonlat) * 0.001 # scale to correct units
File "../python3.6/site-packages/wagl-5.0.3+2.g69df1a4-py3.6-linux-x86_64.egg/wagl/data.py", line 30, in get_pixel
data = src.read(band, window=((y, y + 1), (x, x + 1))).flat[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
~~~~

**Comment by sixy6e** [comment]
For the time being, I can put a simple specific Ancillary Exception into action.  Something along the lines of:

```python
class AncillaryError(Exception):
    pass

try:
    read_elevation(source)
except IndexError:
    raise AncillaryError("No Elevation data")
```

Is something like that ok for the time being?  I think there is need for a more structured Exception handling, potentially with key codes or something that is makes it even easier for [jq](https://stedolan.github.io/jq/) to interpret the json logs.

**Comment by ASVincent** [comment]
Looks like a good improvement in order to start identifying where wagl may exit.

**Comment by sixy6e** [comment]
A new issue has been created for better exception handling for the entirety of wagl.  See #221
